//=============================================================================================================================
// *** START: Configure and import everything related to our Charmap usage ***
//=============================================================================================================================
//----------------------------------------------------------------------------------------------------------------------------
// The constants below define the dimensions and layout of the map and tiles for this program.
// All names starting with CM_ are related to the Charmap configuration and display settings.
// You must define these BEFORE including the Charmap processing code.
//----------------------------------------------------------------------------------------------------------------------------
.const CM_TILE_CHAR_WIDTH = 1              // width in chars of each map tile in the files (1x1 basically means no tiles)
.const CM_TILE_CHAR_HEIGHT = 1             // height in chars of each map tile in the files
.const CM_MAP_TILE_WIDTH = 240             // width in tiles of the map in the files
.const CM_MAP_TILE_HEIGHT = 25             // height in tiles of the map in the files

// set these to how you want the map displayed on the screen
.const CM_DISPLAYED_MAP_X = 0               // upper left corner X coordinate of the map display
.const CM_DISPLAYED_MAP_Y = 0               // upper left corner Y coordinate of the map display
.const CM_DISPLAYED_MAP_TILE_WIDTH = 40     // width in tiles of the displayed map area
.const CM_DISPLAYED_MAP_TILE_HEIGHT = 25    // height in tiles of the displayed map area

.const CODE_START_ADDR = $0810          // where the code starts

#import "./kickasslibs/charmap_import.asm" // import the Charmap processing code

//----------------------------------------------------------------------------------------------------------------------------
// Map data for the level.
// INCLUDE THE MAP DATA FILES GENERATED BY CHARPAD HERE
//----------------------------------------------------------------------------------------------------------------------------
* = CM_CHARSET_CHAR_DATA_ADDR "Charset Data"
        .import binary "./charmap/DemoMap1/DemoMap1 - Chars.bin"
* = CM_CHARSET_ATTRIB_DATA_ADDR "Charset Colors"
        .import binary "./charmap/DemoMap1/DemoMap1 - CharAttribs.bin"
* = CM_MAP_LEVEL_DATA_ADDR "Map Data"
        .import binary "./charmap/DemoMap1/DemoMap1 - Map (240x25).bin"
* = CM_MAP_TILES_DATA_ADDR "Map tiles"
      //.import binary "./charmap/DemoMap1/tiles.bin"  // uncomment this is you have a tiles file from charpad
//=============================================================================================================================
// *** END: Configure and import everything related to our Charmap usage ***
//=============================================================================================================================

.const SPRITE_BANK1_ADDR = $3200        // where sprite data gets loaded - ????

* = SPRITE_BANK1_ADDR "Bank 1 Sprites 176-216"
      //.import binary "sprites.bin"

//----------------------------------------------------------------------------------------------------------------------------
// Code start for the basic upstart routine
//----------------------------------------------------------------------------------------------------------------------------
* = CODE_START_ADDR "Basic Upstart"
smx: .byte
smy: .byte  

BasicUpstart2(start)

//----------------------------------------------------------------------------------------------------------------------------
// main program entry point
//----------------------------------------------------------------------------------------------------------------------------
start:
        KillBASIC()                                  // Disable BASIC to free up RAM
        KillKernal()                                 // Disable KERNAL ROM to free up RAM
        KillCharacterGenerator()                     // Disable Character Generator ROM to free up RAM
        ClearScreen($5b)

        sei
        SetColors(YELLOW, BLACK, ORANGE, LIGHT_GREEN, BROWN)  // Set border and background colors that get used for the map chars
        SetMulticolorMode()                          // Enable multicolor mode
        //Set38ColumnMode()                          // Enable 38-column mode
        SetLowerCaseCharsetMode()                    // make sure we using a charset with upper and lower case characters for the screen codes
        SetCharsetAddress(VIC_SCREEN_CHAR_BANK_OFFSET_10240)   // Set the address of the character set data this offset matches CHARSET_CHAR_DATA_ADDR $2800

// TODO need to get the raster IRQ routines working.        
//        InstallRasterIRQHandlerNotChained(handler, 150, false)
        CMInitCharMapCode()

loop:
        lda #$00 // let's just scroll over and over and over
        sta smx
loop1:
        //CMSetMapYCharOffset(smx)
        CMSetMapXCharOffset(smx)
        jsr CMDrawMapWindowedLUTPointers

        ldx smx ; inx ; stx smx

        //cpx #CM_MAP_MAX_SCROLL_Y
        cpx #CM_MAP_MAX_SCROLL_X
        bne loop1

        jmp loop                // Main loop

//--------------------------------------------
// Wait for vertical blank
//--------------------------------------------
sync_vblank:
        lda VIC_SCREEN_REG_CONTROL1_ADDR
        bpl sync_vblank
!:      lda VIC_SCREEN_REG_CONTROL1_ADDR
        bmi !-
        rts


/* TODO:implement the smooth scrolling logic for horizontal movement 
//--------------------------------------------
// Scrolling logic
//--------------------------------------------
do_scroll:
        lda VIC.REG_CONTROL2_ADDR
        and VIC.REG_CONTROL2_BITS.SMOOTH_SCROLLX_BITS  // Mask out the fine scroll bits (0-7)
        beq coarse_scroll
        dec VIC.REG_CONTROL2_ADDR // Fine scroll: just decrement the register value to move pixels left
        rts

coarse_scroll:
        // Reset fine scroll hardware register back to 7
        lda VIC.REG_CONTROL2_ADDR
//        and #($FF & VIC.REG_CONTROL2_BITS.SMOOTH_SCROLLX_BITS)
        and $FF & VIC.REG_CONTROL2_BITS.SMOOTH_SCROLLX_BITS
        ora VIC.REG_CONTROL2_BITS.SMOOTH_SCROLLX_BITS
        sta VIC.REG_CONTROL2_ADDR
        
        jsr shift_screen // 1. Shift the entire screen left by 1 column
        
        jsr draw_new_column // 2. Inject the next column from the CharPad map

        // 3. Move our map data window pointer right by 1 column
        inc map_char_pointer
        bne !+
        inc map_char_pointer+1
!:
        inc map_color_pointer
        bne !+
        inc map_color_pointer+1
!:      rts

//--------------------------------------------
// shift the contents of the screen left by one column
//--------------------------------------------
shift_screen:
        ldx #0
shift_char_start:  
        // Pull byte from column+1 and write it to current column
        lda VIC.SCREEN.CHAR_MEMORY_ADDR + (0 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.CHAR_MEMORY_ADDR + (0 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.CHAR_MEMORY_ADDR + (1 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.CHAR_MEMORY_ADDR + (1 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.CHAR_MEMORY_ADDR + (2 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.CHAR_MEMORY_ADDR + (2 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.CHAR_MEMORY_ADDR + (3 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.CHAR_MEMORY_ADDR + (3 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.CHAR_MEMORY_ADDR + (4 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.CHAR_MEMORY_ADDR + (4 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.CHAR_MEMORY_ADDR + (5 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.CHAR_MEMORY_ADDR + (5 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.CHAR_MEMORY_ADDR + (6 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.CHAR_MEMORY_ADDR + (6 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.CHAR_MEMORY_ADDR + (7 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.CHAR_MEMORY_ADDR + (7 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.CHAR_MEMORY_ADDR + (8 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.CHAR_MEMORY_ADDR + (8 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.CHAR_MEMORY_ADDR + (9 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.CHAR_MEMORY_ADDR + (9 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.CHAR_MEMORY_ADDR + (10 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.CHAR_MEMORY_ADDR + (10 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.CHAR_MEMORY_ADDR + (11 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.CHAR_MEMORY_ADDR + (11 * VIC.SCREEN.WIDTH_COLS), x
        inx
        cpx #VIC.SCREEN.WIDTH_COLS - 1 // Shift 39 columns wide
        bne shift_char_start
        ldx #0
shift_char_finish:
        lda VIC.SCREEN.CHAR_MEMORY_ADDR + (12 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.CHAR_MEMORY_ADDR + (12 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.CHAR_MEMORY_ADDR + (13 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.CHAR_MEMORY_ADDR + (13 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.CHAR_MEMORY_ADDR + (14 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.CHAR_MEMORY_ADDR + (14 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.CHAR_MEMORY_ADDR + (15 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.CHAR_MEMORY_ADDR + (15 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.CHAR_MEMORY_ADDR + (16 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.CHAR_MEMORY_ADDR + (16 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.CHAR_MEMORY_ADDR + (17 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.CHAR_MEMORY_ADDR + (17 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.CHAR_MEMORY_ADDR + (18 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.CHAR_MEMORY_ADDR + (18 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.CHAR_MEMORY_ADDR + (19 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.CHAR_MEMORY_ADDR + (19 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.CHAR_MEMORY_ADDR + (20 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.CHAR_MEMORY_ADDR + (20 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.CHAR_MEMORY_ADDR + (21 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.CHAR_MEMORY_ADDR + (21 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.CHAR_MEMORY_ADDR + (22 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.CHAR_MEMORY_ADDR + (22 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.CHAR_MEMORY_ADDR + (23 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.CHAR_MEMORY_ADDR + (23 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.CHAR_MEMORY_ADDR + (24 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.CHAR_MEMORY_ADDR + (24 * VIC.SCREEN.WIDTH_COLS), x
        inx
        cpx #VIC.SCREEN.WIDTH_COLS - 1 // Shift 39 columns wide
        bne shift_char_finish

        ldx #0
shift_clr_start:
        // Pull byte from column+1 and write it to current column
        lda VIC.SCREEN.COLOR_MEMORY_ADDR + (0 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.COLOR_MEMORY_ADDR + (0 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.COLOR_MEMORY_ADDR + (1 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.COLOR_MEMORY_ADDR + (1 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.COLOR_MEMORY_ADDR + (2 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.COLOR_MEMORY_ADDR + (2 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.COLOR_MEMORY_ADDR + (3 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.COLOR_MEMORY_ADDR + (3 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.COLOR_MEMORY_ADDR + (4 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.COLOR_MEMORY_ADDR + (4 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.COLOR_MEMORY_ADDR + (5 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.COLOR_MEMORY_ADDR + (5 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.COLOR_MEMORY_ADDR + (6 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.COLOR_MEMORY_ADDR + (6 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.COLOR_MEMORY_ADDR + (7 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.COLOR_MEMORY_ADDR + (7 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.COLOR_MEMORY_ADDR + (8 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.COLOR_MEMORY_ADDR + (8 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.COLOR_MEMORY_ADDR + (9 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.COLOR_MEMORY_ADDR + (9 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.COLOR_MEMORY_ADDR + (10 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.COLOR_MEMORY_ADDR + (10 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.COLOR_MEMORY_ADDR + (11 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.COLOR_MEMORY_ADDR + (11 * VIC.SCREEN.WIDTH_COLS), x
        inx
        cpx #VIC.SCREEN.WIDTH_COLS - 1 // Shift 39 columns wide
        bne shift_clr_start
        ldx #0
shift_clr_finish:
        lda VIC.SCREEN.COLOR_MEMORY_ADDR + (12 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.COLOR_MEMORY_ADDR + (12 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.COLOR_MEMORY_ADDR + (13 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.COLOR_MEMORY_ADDR + (13 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.COLOR_MEMORY_ADDR + (14 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.COLOR_MEMORY_ADDR + (14 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.COLOR_MEMORY_ADDR + (15 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.COLOR_MEMORY_ADDR + (15 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.COLOR_MEMORY_ADDR + (16 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.COLOR_MEMORY_ADDR + (16 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.COLOR_MEMORY_ADDR + (17 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.COLOR_MEMORY_ADDR + (17 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.COLOR_MEMORY_ADDR + (18 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.COLOR_MEMORY_ADDR + (18 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.COLOR_MEMORY_ADDR + (19 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.COLOR_MEMORY_ADDR + (19 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.COLOR_MEMORY_ADDR + (20 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.COLOR_MEMORY_ADDR + (20 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.COLOR_MEMORY_ADDR + (21 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.COLOR_MEMORY_ADDR + (21 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.COLOR_MEMORY_ADDR + (22 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.COLOR_MEMORY_ADDR + (22 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.COLOR_MEMORY_ADDR + (23 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.COLOR_MEMORY_ADDR + (23 * VIC.SCREEN.WIDTH_COLS), x
        lda VIC.SCREEN.COLOR_MEMORY_ADDR + (24 * VIC.SCREEN.WIDTH_COLS) + 1, x
        sta VIC.SCREEN.COLOR_MEMORY_ADDR + (24 * VIC.SCREEN.WIDTH_COLS), x
        inx
        cpx #VIC.SCREEN.WIDTH_COLS - 1 // Shift 39 columns wide
        bne shift_clr_finish
        rts
*/