//=============================================================================================================================
// *** START: Configure and import everything related to our Charmap usage ***
//=============================================================================================================================
//----------------------------------------------------------------------------------------------------------------------------
// The constants below define the dimensions and layout of the map and tiles for this program.
// All names starting with CM_ are related to the Charmap configuration and display settings.
// You must define these BEFORE including the Charmap processing code.
//----------------------------------------------------------------------------------------------------------------------------
.const CM_TILE_CHAR_WIDTH = 1              // width in chars of each map tile in the files (1x1 basically means no tiles)
.const CM_TILE_CHAR_HEIGHT = 1             // height in chars of each map tile in the files
.const CM_MAP_TILE_WIDTH = 240             // width in tiles of the map in the files
.const CM_MAP_TILE_HEIGHT = 25             // height in tiles of the map in the files

// set these to how you want the map displayed on the screen
.const CM_DISPLAYED_MAP_X = 0               // upper left corner X coordinate of the map display
.const CM_DISPLAYED_MAP_Y = 0               // upper left corner Y coordinate of the map display
.const CM_DISPLAYED_MAP_TILE_WIDTH = 40     // width in tiles of the displayed map area
.const CM_DISPLAYED_MAP_TILE_HEIGHT = 25    // height in tiles of the displayed map area

.const CODE_START_ADDR = $0810          // where the code starts

#import "./kickasslibs/charmap_import.asm" // import the Charmap processing code

//----------------------------------------------------------------------------------------------------------------------------
// Map data for the level.
// INCLUDE THE MAP DATA FILES GENERATED BY CHARPAD HERE
//----------------------------------------------------------------------------------------------------------------------------
* = CM_CHARSET_CHAR_DATA_ADDR "Charset Data"
        .import binary "./charmap/DemoMap1/DemoMap1 - Chars.bin"
* = CM_CHARSET_ATTRIB_DATA_ADDR "Charset Colors"
        .import binary "./charmap/DemoMap1/DemoMap1 - CharAttribs.bin"
* = CM_MAP_LEVEL_DATA_ADDR "Map Data"
        .import binary "./charmap/DemoMap1/DemoMap1 - Map (240x25).bin"
//=============================================================================================================================
// *** END: Configure and import everything related to our Charmap usage ***
//=============================================================================================================================

//----------------------------------------------------------------------------------------------------------------------------
// Code start for the basic upstart routine
//----------------------------------------------------------------------------------------------------------------------------
* = CODE_START_ADDR "Basic Upstart"
smx: .byte
smy: .byte  

BasicUpstart2(start)

//----------------------------------------------------------------------------------------------------------------------------
// main program entry point
//----------------------------------------------------------------------------------------------------------------------------
start:
        KillBASIC()                                  // Disable BASIC to free up RAM
        KillKernal()                                 // Disable KERNAL ROM to free up RAM
        KillCharacterGenerator()                     // Disable Character Generator ROM to free up RAM
        ClearScreen($5b)

        sei
        SetColors(YELLOW, BLACK, ORANGE, LIGHT_GREEN, BROWN)                    // Set border and background colors that get used for the map chars
        SetMulticolorMode()                          // Enable multicolor mode
        //Set38ColumnMode()                          // Enable 38-column mode
        SetLowerCaseCharsetMode()                    // make sure we using a charset with upper and lower case characters for the screen codes
        SetCharsetAddress(VIC_SCREEN_CHAR_BANK_OFFSET_10240)   // Set the address of the character set data this offset matches CHARSET_CHAR_DATA_ADDR $2800

// need to get the raster IRQ routines working.        
//        InstallRasterIRQHandlerNotChained(handler, 150, false)
        CMInitCharMapCode()

loop:
        lda #$00
        sta smx
loop1:
        CMSetMapXCharOffset(smx)
        //jsr sync_vblank
        jsr CMDrawMapWindowed

        ldx smx
        inx
        stx smx
        cpx #(CM_MAP_CHAR_WIDTH - CM_DISPLAYED_MAP_CHAR_WIDTH)
        bne loop1

        jmp loop                // Main loop

//--------------------------------------------
// Wait for vertical blank
//--------------------------------------------
sync_vblank:
        lda VIC_SCREEN_REG_CONTROL1_ADDR
        bpl sync_vblank
!:      lda VIC_SCREEN_REG_CONTROL1_ADDR
        bmi !-
        rts
