//=============================================================================================================================
// *** START: Configure and import everything related to our Charmap usage ***
// This demo shows full screen horizontal smooth scrolling with a large map (240x25).
//=============================================================================================================================
//----------------------------------------------------------------------------------------------------------------------------
// The constants below define the dimensions and layout of the map and tiles for this program.
// All names starting with CM_ are related to the Charmap configuration and display settings.
// You must define these BEFORE including the Charmap processing code.
//----------------------------------------------------------------------------------------------------------------------------
.const CM_TILE_CHAR_WIDTH = 1              // width in chars of each map tile in the files (1x1 means no tiles)
.const CM_TILE_CHAR_HEIGHT = 1             // height in chars of each map tile in the files
.const CM_MAP_TILE_WIDTH = 240             // width in tiles of the map in the files
.const CM_MAP_TILE_HEIGHT = 25             // height in tiles of the map in the files

// set these to how you want the map displayed on the screen
.const CM_DISPLAYED_MAP_X = 0               // upper left corner X coordinate of the map display
.const CM_DISPLAYED_MAP_Y = 0               // upper left corner Y coordinate of the map display
.const CM_DISPLAYED_MAP_TILE_WIDTH = 40     // width in tiles of the displayed map area
.const CM_DISPLAYED_MAP_TILE_HEIGHT = 25    // height in tiles of the displayed map area

.const CODE_START_ADDR = $5500//$C800          // where the code starts

BasicUpstart2(start)
* = CODE_START_ADDR "CODE_START_ADDR"

#import "../kickasslibs/charmap_import.asm" // import the Charmap processing code
//=============================================================================================================================
// *** END: Configure and import everything related to our Charmap usage ***
//=============================================================================================================================

//----------------------------------------------------------------------------------------------------------------------------
// program entry point
//----------------------------------------------------------------------------------------------------------------------------
start:
        DefaultGameInit()   // Initialize the game with default settings

        //------------------------------------------------------------------------------------------------------
        // this is how you use the map with smooth horizontal scrolling
        // when using smooth scrolling the code will automatically draw the screen when needed
        // and flip the buffers as needed to maintain smooth scrolling
        //------------------------------------------------------------------------------------------------------
scrollLeft: // scroll the map to the left until the x position reaches 200 (map is 240 chars wide)
//.break
        CMHorizontalSmoothScrollLeftOnePixel()  
        lda cm_CurrentCharScrollXPosition
        cmp #$C8 //200
        bne scrollLeft
scrollRight: // scroll the map to the right until the x position reaches 0
        CMHorizontalSmoothScrollRightOnePixel()  
        lda cm_CurrentCharScrollXPosition
        cmp #$0
        bne scrollRight
        jmp scrollLeft

//----------------------------------------------------------------------------------------------------------------------------
// Map data for the level.
// INCLUDE THE MAP DATA FILES GENERATED BY CHARPAD HERE
//----------------------------------------------------------------------------------------------------------------------------
* = CM_CHARSET_CHAR_DATA_ADDR "CHARSET_CHAR_DATA_ADDR"
.align $100
        .import binary "../charmap/DemoMap1/DemoMap1 - Chars.bin"
* = CM_CHARSET_ATTRIB_DATA_ADDR "CHARSET_ATTRIB_DATA_ADDR"
.align $100
        .import binary "../charmap/DemoMap1/DemoMap1 - CharAttribs.bin"
* = CM_MAP_LEVEL_DATA_ADDR "MAP_LEVEL_DATA_ADDR"
.align $100
        .import binary "../charmap/DemoMap1/DemoMap1 - Map (240x25).bin"
